"use client";
import Link from "next/link";
import { useAccount } from "wagmi";
import Section from "~/components/common/Section";
import SirCard from "~/components/common/SirCard";
import Image from "next/image";
import { api } from "~/trpc/react";
import Allocations from "~/components/Allocations";

export default function AllocationsPage() {
  const { address: user, isConnected } = useAccount();

  const { data: buterinCards } = api.nfts.fetchWalletButerinCards.useQuery(
    user,
    {
      enabled: isConnected,
    },
  );

  const { data: minedJpegs } = api.nfts.fetchWalletMinedJpeg.useQuery(user, {
    enabled: isConnected,
  });

  console.log({
    user,
    buterinCards,
    minedJpegs,
  });

  const bullets = [
    {
      i: 1,
      text: 'We are conducting multiple private protocol <span class="font-semibold text-redAccent">code audits with different security firms</span> and plan a public audit as well. After identifying and fixing any important bugs, we will proceed with the <span class="font-semibold text-redAccent">mainnet relaunch</span>.',
    },
    {
      i: 2,
      text: 'During the initial three-year period, <span class="font-semibold text-redAccent">tokens will unlock linearly</span>. After this phase, all newly issued tokens will be allocated exclusively to liquidity providers.',
    },
    {
      i: 3,
      text: 'As a <span class="font-semibold text-redAccent">revenue-sharing token</span>, SIR entitles stakers to a percentage of the fees generated by the protocol, converted and <span class="font-semibold text-redAccent">paid out in ETH</span>. For a more detailed explanation, please refer to <a href="https://docs.sir.trading/" target="_blank" class="underline">our documentation</a>.',
    },
  ];

  const chartLegend = [
    { label: "Liquidity providers", color: "bg-[#CC9901]" },
    { label: "Team & Contributors", color: "bg-[#6A3C99]" },
    { label: "Presale", color: "bg-[#CC6677]" },
    { label: "Treasury", color: "bg-[#882255]" },
    { label: "Compensation fund (victims of the hack)", color: "bg-[#117733]" },
  ];

  return (
    <div className="container">
      <Section variant="background" header={"Your Allocation"}>
        <div className="section-text-block p-4">
          <p>
            We captured{" "}
            <span className="text-redAccent font-semibold">a snapshot</span> of
            every user’s on-chain data at{" "}
            <span className="text-redAccent font-semibold">
              block #22,157,899
            </span>
            , detailing SIR balances, leverage positions, liquidity-provision
            stakes and more just before{" "}
            <a
              href="https://etherscan.io/tx/0xa05f047ddfdad9126624c4496b5d4a59f961ee7c091e7b4e38cee86f1335736f"
              className="underline"
              target="_blank"
            >
              the exploit
            </a>
            .
          </p>
          <p>
            To calculate each{" "}
            <span className="text-redAccent font-semibold">
              user’s compensation allocation
            </span>{" "}
            at relaunch, we converted all holdings into SIR token using the
            market prices at that exact moment (ETH $1,805; BTC $82,356; USDT
            $0.9998; USDC $1.00; SIR $0.0005955).
          </p>
        </div>
        <Allocations />
      </Section>

      <Section variant="background" header="SIR Token Presale">
        <div className="section-text-block mt-0 mb-6 flex flex-col">
          <p>
            The presale is over. Despite the recent{" "}
            <a
              href="https://x.com/DecurityHQ/status/1906270316935942350"
              target="_blank"
              className="underline"
            >
              exploit of the SIR protocol
            </a>
            , we plan on relaunching very soon.{" "}
            <span className="text-redAccent font-semibold">
              Your original SIR token allocation remains valid
            </span>{" "}
            and will carry over.
          </p>
        </div>
        <div className="flex w-full flex-col items-center md:flex-row md:justify-end">
          {/*<Connect />*/}
        </div>
      </Section>

      {isConnected && (
        <Section variant="background" header="Your Contributions">
          <div className="section-text-block mt-0 mb-6 flex flex-col">
            <p>
              This reflects your allocation of SIR tokens based on your original
              presale participation and number of locked NFTs.
            </p>
            <p>
              <span className="text-redAccent font-semibold">Please note:</span>{" "}
              any tokens sold during the pre-exploit live version of SIR will be
              deducted from your allocation.
            </p>
            {/*<PresaleNftList />*/}
          </div>
        </Section>
      )}

      <Section variant="background" header="Next Steps">
        <div className="flex w-full flex-col items-center gap-20 md:flex-row md:items-start md:justify-evenly md:gap-0">
          {bullets.map((bullet) => (
            <SirCard size="xs" key={bullet.i}>
              <div
                slot="header"
                className="text-rob-roy-300 ring-rob-roy-300 rounded-xl px-4 py-3 text-center font-black ring-2"
              >
                {bullet.i}
              </div>
              <p
                className="text-left md:p-3"
                dangerouslySetInnerHTML={{ __html: bullet.text }}
              />
            </SirCard>
          ))}
        </div>

        <div className="flex w-full flex-col items-center gap-12 p-6 md:flex-row md:justify-evenly md:gap-0">
          <div className="flex w-full flex-col gap-y-8 p-0 md:p-12">
            <p className="flex flex-col font-bold">
              <span>Token issuance</span>
              <span>for the first three years</span>
            </p>
            <Image
              alt="Emissions for the first 3 years"
              src="/presale_first_three_years.png"
              className="mx-auto block h-[345px] w-auto object-contain"
              width={345}
              height={345}
            />
          </div>
          <div className="flex w-full flex-col gap-y-8 p-0 md:p-12">
            <p className="flex flex-col font-bold">
              <span>Token issuance</span>
              <span>after three years</span>
            </p>
            <Image
              alt="Emissions after the 3rd year"
              src="/sale_after_three_years.png"
              className="mx-auto block h-[345px] w-auto object-contain"
              width={345}
              height={345}
            />
          </div>
        </div>

        <div className="flex w-full flex-row flex-wrap items-center justify-center gap-6 p-6">
          {chartLegend.map((item) => (
            <div key={item.label} className="flex items-center gap-1">
              <div className={`h-[1rem] w-[1rem] rounded-full ${item.color}`} />
              {item.label}
            </div>
          ))}
        </div>
      </Section>

      <footer className="flex w-full flex-col items-center justify-center py-10">
        <Link href="/sale_disclaimer">Sale disclaimer</Link>
      </footer>
    </div>
  );
}
