"use client";
import Link from "next/link";
import { useAccount } from "wagmi";
import Section from "~/components/common/Section";
import Image from "next/image";
import { api } from "~/trpc/react";
import Allocations from "~/components/Allocations";
import { CustomConnectButton } from "~/components/customConnectButton";
import Contributions from "~/components/sale/Contributions";

const bullets = [
  {
    i: 1,
    text: (
      <>
        We are conducting multiple private protocol{" "}
        <strong>
          code audits with different security firms
        </strong>{" "}
        and plan a public audit as well. After identifying and fixing any
        important bugs, we will proceed with the{" "}
        <strong>mainnet relaunch</strong>.
      </>
    ),
  },
  {
    i: 2,
    text: (
      <>
        During the initial three-year period,{" "}
        <strong>
          tokens will unlock linearly
        </strong>
        . After this phase, all newly issued tokens will be allocated
        exclusively to liquidity providers.
      </>
    ),
  },
  {
    i: 3,
    text: (
      <>
        As a{" "}
        <strong>
          revenue-sharing token
        </strong>
        , SIR entitles stakers to a percentage of the fees generated by the
        protocol, converted and{" "}
        <strong>paid out in ETH</strong>.
        For a more detailed explanation, please refer to{" "}
        <a
          href="https://docs.sir.trading/"
          target="_blank"
          className="underline"
        >
          our documentation
        </a>
        .
      </>
    ),
  },
];

const chartLegend = [
  { label: "Liquidity providers", color: "bg-[#CC9901]" },
  { label: "Team & Contributors", color: "bg-[#6A3C99]" },
  { label: "Presale", color: "bg-[#CC6677]" },
  { label: "Treasury", color: "bg-[#882255]" },
  { label: "Compensation fund (victims of the hack)", color: "bg-[#117733]" },
];

export default function AllocationsPage() {
  const { address: user, isConnected } = useAccount();

  const { data: buterinCards } = api.nfts.fetchWalletButerinCards.useQuery(
    user,
    {
      enabled: isConnected,
    },
  );

  const { data: minedJpegs } = api.nfts.fetchWalletMinedJpeg.useQuery(user, {
    enabled: isConnected,
  });

  console.log({
    user,
    buterinCards,
    minedJpegs,
  });

  return (
    <div className="container">
      <Section variant="background" header={"Your Allocation"}>
        <div className="section-text-block p-4">
          <p>
            We captured{" "}
            <strong>a snapshot</strong> of every user&aposs on-chain data at{" "}
            <strong>block #22,157,899</strong>
            , detailing SIR balances, leverage positions, liquidity-provision
            stakes and more just before{" "}
            <a
              href="https://etherscan.io/tx/0xa05f047ddfdad9126624c4496b5d4a59f961ee7c091e7b4e38cee86f1335736f"
              className="underline"
              target="_blank"
            >
              the exploit
            </a>
            .
          </p>
          <p>
            To calculate each{" "}
            <strong>user&aposs compensation allocation</strong>{" "}
            at relaunch, we converted all holdings into SIR token using the
            market prices at that exact moment (ETH $1,805; BTC $82,356; USDT
            $0.9998; USDC $1.00; SIR $0.0005955).
          </p>
        </div>
        <Allocations />
      </Section>

      <Section variant="background" header="SIR Token Presale">
        <div className="section-text-block mt-0 mb-6 flex flex-col">
          <p>
            The presale is over. Despite the recent{" "}
            <a
              href="https://x.com/DecurityHQ/status/1906270316935942350"
              target="_blank"
              className="underline"
            >
              exploit of the SIR protocol
            </a>
            , we plan on relaunching very soon.{" "}
            <strong>
              Your original SIR token allocation remains valid
            </strong>{" "}
            and will carry over.
          </p>
        </div>
        <div className="flex w-full flex-col items-center md:flex-row md:justify-end">
          <div className="flex justify-end gap-4">
            <CustomConnectButton />
          </div>
        </div>
      </Section>

      {isConnected && (
        <Section variant="background" header="Your Contributions">
          <div className="section-text-block mt-0 mb-6 flex flex-col">
            <p>
              This reflects your allocation of SIR tokens based on your original
              presale participation and number of locked NFTs.
            </p>
            <p>
              <strong>Please note:</strong>{" "}
              any tokens sold during the pre-exploit live version of SIR will be
              deducted from your allocation.
            </p>
            <Contributions />
          </div>
        </Section>
      )}

      <Section variant="background" header="Next Steps">
        <div className="flex w-full flex-col items-center gap-20 md:flex-row md:items-start md:justify-evenly md:gap-6">
          {bullets.map((bullet) => (
            <div key={bullet.i} className="flex flex-col flex-1 basis-0">
              <span className="relative grid place-items-center w-15 h-15 shrink-0 mx-auto">
                <span aria-hidden className="neon-badge absolute inset-0" />
                <span className="absolute inset-0 flex items-center justify-center font-semibold">
                  {bullet.i}
                </span>
              </span>
              <p className="text-justify text-balance hyphens-auto md:p-3">{bullet.text}</p>
            </div>
          ))}
        </div>

        <div className="flex w-full flex-col items-center gap-12 p-6 md:flex-row md:justify-evenly md:gap-0">
          <div className="flex w-full flex-col gap-y-8 p-0 md:p-12">
            <p className="flex flex-col font-bold">
              <span>Token issuance</span>
              <span>for the first three years</span>
            </p>
            <Image
              alt="Emissions for the first 3 years"
              src="/presale_first_three_years.png"
              className="mx-auto block h-[345px] w-auto object-contain"
              width={345}
              height={345}
            />
          </div>
          <div className="flex w-full flex-col gap-y-8 p-0 md:p-12">
            <p className="flex flex-col font-bold">
              <span>Token issuance</span>
              <span>after three years</span>
            </p>
            <Image
              alt="Emissions after the 3rd year"
              src="/sale_after_three_years.png"
              className="mx-auto block h-[345px] w-auto object-contain"
              width={345}
              height={345}
            />
          </div>
        </div>

        <div className="flex w-full flex-row flex-wrap items-center justify-center gap-6 p-6">
          {chartLegend.map((item) => (
            <div key={item.label} className="flex items-center gap-1">
              <div className={`h-[1rem] w-[1rem] ${item.color}`} />
              {item.label}
            </div>
          ))}
        </div>
      </Section>

      <footer className="flex w-full flex-col items-center justify-center py-10">
        <Link href="/sale_disclaimer">Sale disclaimer</Link>
      </footer>
    </div>
  );
}
